### ISSUE TITLE
Release :)

### ISSUE THREAD

**Issue by deejay87** [HookedBehemoth/sys-tune#1]
Hello
Any release date for testing this ? 
Thanks :)

**Comment by HookedBehemoth** [comment]
Thanks for your interest ;)
Currently waiting out for the issues around 10.0.0, AMS and Tesla to get resolved.

**Comment by deejay87** [comment]
Ok , waiting so , thanks

**Comment by HookedBehemoth** [comment]
Done https://github.com/HookedBehemoth/sys-tune/releases :+1:
