### ISSUE TITLE
Support for utf8 characters

### ISSUE THREAD

**Issue by pseiler** [HookedBehemoth/sys-tune#14]
When I try to enter a music directory containing some umlauts (f.e. an "Ä") I get this error:
```
Something went wrong :/
2002-0001
```
Also the umlaut isn't displayed properly. It gets replaced with an underscore. 

If I try to play a mp3 file with an umlaut it won't do anything.

This seems an encoding issue to me. Adding support for / switch to utf8 encoding should fix this issue.

**Comment by HookedBehemoth** [comment]
Pretty sure that's an issue with Nintendo's broken FAT drivers.
I'll look into it.

**Comment by pseiler** [comment]
Thank you very much. Looking forward to it!

**Comment by HookedBehemoth** [comment]
According to SciresM (atmosphere lead programmer):
The issue with the FAT driver implementation is that prFILE2 deals in SJIS but the interface to it encodes everything with UTF-8.
The information that ends up on my end is just: these files/folders are named `_` or `Mot_rhead`
So now you want to open that file and you give the filesystem sysmodule the name of the file.
That checks back with prFILE2 drivers and they have never heard of a folder called `Mot_rhead`.
This is 100% Nintendos fault and I can't do much about this.
SciresM plans to reimplement the fs sysmodule in 2021-2022.
https://github.com/Atmosphere-NX/Atmosphere/blob/master/docs/roadmap.md#fs-reimplementation

**Comment by pseiler** [comment]
Sad news. I come back when the fs code got reimplemented.
Thank you for your effort. This is a really cool project.

**Comment by HookedBehemoth** [comment]
Closing this as this needs to be fixed somewhere else.

Either Nintendo fixes their drivers or atmosphere re-implements the FS sysmodule.

**Comment by HookedBehemoth** [comment]
Great News!
SciresM is working on a fix for this double encoding issue.
So this might be resolved relatively soon and we don't have to wait for fs reimplementation.

**Comment by pseiler** [comment]
This sounds awesome. Looking forward to it!
