### ISSUE TITLE
something went wrong:/ 2002-1775

### ISSUE THREAD

**Issue by muxi1** [HookedBehemoth/sys-tune#17]
Hi @HookedBehemoth 

When I open the Music Browser under v1.2.0 the error "something went wrong:/ 2002-1775" occurs and the Tesla menu can no longer be used without a reboot. This problem does not exist under v1.1.2.

I´m on AMS 0.13.0|E / FW 10.0.4 

Tesla menu and nx-ovlloader are also up to date.

**Comment by iixela** [comment]
I have the same problem.. :(

**Comment by HookedBehemoth** [comment]
should be fixed by this: https://github.com/HookedBehemoth/sys-tune/releases/tag/v1.2.1

**Comment by iixela** [comment]
Thanks a lot!
