### ISSUE TITLE
Playback based on titleID (specifically the Home Menu)

### ISSUE THREAD

**Issue by QTKO** [HookedBehemoth/sys-tune#19]
Since NXThemes currently don't support background music, I was hoping for a makeshift alternative by only playing background music in the Home Menu's titleID. I know that sys-audioplayer had this function, but it hasn't been updated since 9.0.0. Is there any chance this will be implemented in sys-tune? And if not, would it be possible to have a titleID whitelist/blacklist to determine when sys-tune is allowed to play?

**Comment by HookedBehemoth** [comment]
How would you propose this should be used?
I would like to have everything be configurable from the companion overlay.

**Comment by LillianGoulston** [comment]
If everything needs to be in the overlay, then maybe having a checklist/list of toggles based on installed titles, and users can choose which ones allow music from sys-tune.

**Comment by ITotalJustice** [comment]
added in https://github.com/HookedBehemoth/sys-tune/pull/35
