### ISSUE TITLE
failed to lunch sysmodule "2005-0012"

### ISSUE THREAD

**Issue by salem193** [HookedBehemoth/sys-tune#20]
hi @HookedBehemoth 

i was using“sys-tune” since one week but yesterday tried to open it as usual But this error message appeared “Failed to launch sysmodule .2005-0012“

FW: SXOS 3.0.5 / FW: 10.2.0

sys-tune 1.2.1
Tesla menu 1.1.3
nx-ovlloader 1.0.6

**Comment by HookedBehemoth** [comment]
Does this also happen on Atmosphère?

**Comment by salem193** [comment]
i am SXOS user so i don't know if that happen also with Atmosphère

**Comment by HookedBehemoth** [comment]
closing because I can't reproduce
