### ISSUE TITLE
Add 13.x.x support.

### ISSUE THREAD

**Issue by nanashi89** [HookedBehemoth/sys-tune#23]
Just updated to 13.0.0. Support for that firmware would be nice.

Please?

Thanks!

**Comment by cucholix** [comment]
It works in fw 13.0.0 | ams 1.1.0
![AFD05530-261E-445C-B129-773AFABD7B53](https://user-images.githubusercontent.com/16081693/134257187-b2692c7f-e7c1-4fbe-8708-2898605da9b9.jpeg)
![08165EBC-1E66-4684-9128-0B5058A1BD1B](https://user-images.githubusercontent.com/16081693/134257195-f544d436-e5ea-4e47-a633-2dc2d4657cc5.jpeg)
![2478C7A1-59E7-4A8D-8BA6-327BF7E81C71](https://user-images.githubusercontent.com/16081693/134257198-6a67dc9c-7b64-4ad6-b48d-ea57b2fa160c.jpeg)
