### ISSUE TITLE
For some reason music just won't play

### ISSUE THREAD

**Issue by Littlebigdwolf** [HookedBehemoth/sys-tune#25]
I don't know why but when I go to the menu, go to music browser, then press a on one of my songs then it doesn't play and still says "Stopped!"

**Comment by billycollinz** [comment]
I am having the same issue. Haven’t found any fixes yet.

**Comment by Auseronline202** [comment]
I have the same issue but only one song can play. I did a redo of everything and it still didn't work.

**Comment by BlackLoner** [comment]
I recommend to adjust the volume of the songs by using Audacity, It fixed this issue to me
