### ISSUE TITLE
Crash on 15.0.0.1

### ISSUE THREAD

**Issue by ThePikaFlo** [HookedBehemoth/sys-tune#27]
It's just not working anymore on the newest version. Any fix?

**Comment by HookedBehemoth** [comment]
It works on mine on the latest version (15.0.0) and Atmosphère 1.4.0.
Can you please provide more details? Under what circumstance does it crash?
What's the program ID shown in the crash screen?
Please also attach the corresponding crash report from `/atmosphere/crash_reports` and/or fatal report from `/atmosphere/fatal_reports`.

**Comment by ThePikaFlo** [comment]
Strange. I get exactly a crash after the switch logo.

Error Code: 2168-0001

Program: 42000000000007E51A
Firmware: 15.0.1

I'm using those versions:
TESLA menu: https://github.com/WerWolv/Tesla-Menu/releases/tag/v1.2.0
NxOvlloader: https://github.com/WerWolv/nx-ovlloader/releases/tag/v1.0.6
Sys-tune: The last version.

**Comment by HookedBehemoth** [comment]
Without the crash report I can't tell.
It's probably a memory issue. You need to disable/remove system modules.

**Comment by ThePikaFlo** [comment]
Well here's the crash report.
[01671728604_420000000007e51a.log](https://github.com/HookedBehemoth/sys-tune/files/10290325/01671728604_420000000007e51a.log)

**Comment by HookedBehemoth** [comment]
As this is an issue with the overlay menu and not sys-tune, I'll close this issue.
