### ISSUE TITLE
It would be useful to be able to reproduce a folder as a playlist

### ISSUE THREAD

**Issue by Gullib** [HookedBehemoth/sys-tune#3]
It is a bit annoying having to individually click each song to add to the playlist. Why cant we just select a folder o be a playlist, that wold be pretty neat.

**Comment by HookedBehemoth** [comment]
Currently I'm missing the features to do that in libtesla. I've thought of a few ways of doing that and it will be an option in the future.

**Comment by ITotalJustice** [comment]
looks like this can be closed because of https://github.com/HookedBehemoth/sys-tune/commit/8ffce070a52a41124ed93aeb975e3d5ef4ab680a
