### ISSUE TITLE
Some games crashing the audio module with Error 2162-0002

### ISSUE THREAD

**Issue by EasedVR** [HookedBehemoth/sys-tune#31]
Hello,
as soon as I start sys-tune v1.2.2 on FW 16.0.0 and Atmosphere 1.5.0, the switch crashes on some games with a blue screen with error 2162-0002 on program id 0100000000000014, which seems to be the audio module according to Google.
Triplayer has the same problem, but that isn't updated for FW 16.0.0 anyway.

Some examples of games crashing:
Nintendo Entertainment System NSO (crashing when I start the emulator)
Gameboy Advanced NSO (crashing when starting a game)

I attached the crash report.
Thank you for making this audio player.
[01677917063_0100000000000014.log](https://github.com/HookedBehemoth/sys-tune/files/10887822/01677917063_0100000000000014.log)

**Comment by ITotalJustice** [comment]
workaround added in https://github.com/HookedBehemoth/sys-tune/pull/35
