### ISSUE TITLE
options for music to just be assigned to home menu only 

### ISSUE THREAD

**Issue by carr654** [HookedBehemoth/sys-tune#33]
It would be nice to hear chill music on the home theme without it interfering with the game music. just like xor play used to do but i asked them and they wont update due to other projects they work on and refered me to use this but its not exact what i would like. so would be entirely greatful if we had the possibly to just assign music to home menu as i like to be able to hear game play when in game and music when not in game. https://github.com/XorTroll/ModuleMania/tree/master/xor.play

**Comment by ITotalJustice** [comment]
fixed in https://github.com/HookedBehemoth/sys-tune/pull/35
