### ISSUE TITLE
Forward/Rewind

### ISSUE THREAD

**Issue by dacaskos** [HookedBehemoth/sys-tune#4]
Would be possible to achieve that? That would be specially useful with Korg Gadget

**Comment by HookedBehemoth** [comment]
The groundwork for this has been made. Will come in the next release.

**Comment by HookedBehemoth** [comment]
Implemented on [dev](https://github.com/HookedBehemoth/sys-tune/tree/dev)
Will keep this open until the next update.

**Comment by HookedBehemoth** [comment]
https://github.com/HookedBehemoth/sys-tune/releases/tag/v1.1.2
