### ISSUE TITLE
FLAC support

### ISSUE THREAD

**Issue by fennectech** [HookedBehemoth/sys-tune#5]
I love this   But the vast majority of my library is in flac format   Id love the ability to play flac as well as mp3 As for the memory issue you could produce multiple versions   One for mp3 only and one for mp3&flac   Package bolth exefs.nsp and copy one to exefs.nsp when switching modes

**Comment by HookedBehemoth** [comment]
Looking at dr_flac rn and I like the api so far.

**Comment by HookedBehemoth** [comment]
Since resampling flac's isn't trivial I'll have to move on from audout to audrv (uses audren).

This will bring another major positiv extra: No more sleep 

It will require quite some work tho since I'm unfamiliar with the interface.

**Comment by HookedBehemoth** [comment]
No more sleep issues*

LMAO

**Comment by fennectech** [comment]
so  Is this actually goging to be a thing or do i need to start the long process of converting 70 gigs of music to MP3 for it

**Comment by HookedBehemoth** [comment]
Give me some time to figure out how audren/audrv works.

Decoding works fine for now but you wouldn't be happy with 44100Hz flac's being interpreted at 48000Hz.

**Comment by HookedBehemoth** [comment]
Implemented on [dev](https://github.com/HookedBehemoth/sys-tune/tree/dev)
Will keep this open until the next update.

**Comment by Sword09** [comment]
you're amazing I just wanted to say that :)
Do you have a discord for your projects ?

**Comment by HookedBehemoth** [comment]
Not really active yet but feel free to join.
https://discord.gg/eW5CX4

**Comment by fennectech** [comment]
They are pretty active on atlasNX

**Comment by Sword09** [comment]
Looks like the discord invite link is dead

**Comment by HookedBehemoth** [comment]
fixed

**Comment by HookedBehemoth** [comment]
https://github.com/HookedBehemoth/sys-tune/releases/tag/v1.1.2
